defaults:
  upx: true
  username: whzhni  # 默认用户名（所有平台通用）
  platforms: gitcode gitee gitlab r2
  R2_PUBLIC_URL: https://pub-8a57d35d70d5423aac22a3316867e7ce.r2.dev

projects:
  openlist:
    repo: OpenListTeam/OpenList
    luci_repo: sbwml/luci-app-openlist2
    platforms: r2 gitlab

  vnt:
    repo: vnt-dev/vnt
    luci_repo: lmq8267/luci-app-vnt
    filter: "vnt-*-linux-*"
    exclude: ["*-android-*"]
   # upx: off

  vnts:
    repo: vnt-dev/vnts
    filter: "vnts-*-linux-*"
