# ä¸Šæ¸¸åŒæ­¥é…ç½®
# æ¯ä¸ªé¡¹ç›®çš„é…ç½®è¯´æ˜ï¼š
# - github_owner: GitHub ç”¨æˆ·å/ç»„ç»‡åï¼ˆå¿…å¡«ï¼‰
# - github_repo: GitHub ä»“åº“åï¼ˆå¿…å¡«ï¼‰
# - local_name: æœ¬åœ°ä»“åº“åç§°ï¼ˆé€‰å¡«ï¼Œé»˜è®¤ä½¿ç”¨ github_repoï¼‰
# - platforms: å‘å¸ƒå¹³å°ï¼Œç©ºæ ¼åˆ†éš”ï¼ˆé€‰å¡«ï¼Œé»˜è®¤ï¼šgitcode gitee gitlab r2ï¼‰
#   å¯é€‰å€¼ï¼šgitcode, gitee, gitlab, r2
# - filter_exclude: æ’é™¤æ–‡ä»¶è§„åˆ™ï¼Œç©ºæ ¼åˆ†éš”ï¼ˆé€‰å¡«ï¼‰
# - filter_include: åŒ…å«æ–‡ä»¶è§„åˆ™ï¼Œæ ¼å¼ï¼špattern:æ•°é‡ï¼ˆé€‰å¡«ï¼‰
# - filter_by_version: æ˜¯å¦åªä¿ç•™ç‰ˆæœ¬å·åŒ¹é…çš„æ–‡ä»¶ï¼ˆé€‰å¡«ï¼Œé»˜è®¤ falseï¼‰

# ğŸŒ å…¨å±€é»˜è®¤é…ç½®
defaults:
  username: whzhni  # é»˜è®¤ç”¨æˆ·åï¼ˆæ‰€æœ‰å¹³å°é€šç”¨ï¼‰
  platforms: gitcode gitee gitlab r2  # é»˜è®¤å‘å¸ƒå¹³å°
  R2_PUBLIC_URL: https://pub-8a57d35d70d5423aac22a3316867e7ce.r2.dev # ä½ çš„Cloudflare R2å­˜å‚¨æ¡¶å…¬å…±å¼€å‘ URL
  # GITCODE_USERNAME: abc # è‡ªå®šä¹‰gitcodeç”¨æˆ·å
  # GITEE_USERNAME: def # è‡ªå®šä¹‰giteeç”¨æˆ·å
  # GITLAB_USERNAME: cba # è‡ªå®šä¹‰gitlabç”¨æˆ·å

# ğŸ“¦ ä»“åº“é…ç½®
repositories:
  - github_owner: vernesong
    github_repo: OpenClash
    local_name: luci-app-openclash
    platforms: r2  # åªå‘å¸ƒåˆ°Cloudflare r2
    
  - github_owner: whzhni1
    github_repo: luci-app-tailscale
    local_name: tailscale

  - github_owner: whzhni1
    github_repo: luci-app-lucky
    local_name: lucky

  - github_owner: eamonxg
    github_repo: luci-theme-aurora

  - github_owner: xiaorouji
    github_repo: openwrt-passwall
    local_name: luci-app-passwall
    filter_exclude: luci-19.07* *.zip

  - github_owner: xiaorouji
    github_repo: openwrt-passwall2
    local_name: luci-app-passwall2
    filter_exclude: luci-19.07* *.zip
    
